ProjectSEM3/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MlkPwgen;
using Newtonsoft.Json;
using ProjectSEM3.Data;
using ProjectSEM3.Models;
using SecurityHelper;

namespace ProjectSEM3.Controllers
{
    public class AuthController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly IHttpContextAccessor _httpContextAccessor;
        private ISession _session => _httpContextAccessor.HttpContext.Session;

        public AuthController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;


        }
        public IActionResult Index()
        {
            return View();
        }

        [Route("Login")]
        [Route("Auth/Login")]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignIn([Bind("Username,Password")] Account account)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var existAccount = _context.Account.SingleOrDefault(a => a.Username == account.Username);
            if (existAccount != null)
            {
                if (existAccount.Password == PasswordHandle.GetInstance().EncryptPassword(account.Password, existAccount.Salt))
                {
                    var existCredential = await _context.Credential.SingleOrDefaultAsync(c =>
                            c.OwnerId == existAccount.Id);
                    if (existCredential != null)
                    {
                        var accessToken = PasswordGenerator.Generate(length: 40, allowed: Sets.Alphanumerics);
                        existCredential.AccessToken = accessToken;
                        await _context.SaveChangesAsync();
                        _session.SetString("auth", existCredential.AccessToken);
                    }
                    else
                    {
                        var credential = new Credential(existAccount.Id)
                        {
                            AccessToken = PasswordGenerator.Generate(length: 40, allowed: Sets.Alphanumerics)
                        };
                        _context.Credential.Add(credential);
                        await _context.SaveChangesAsync();
                        _session.SetString("auth", credential.AccessToken);

                    }
                    _session.SetString("user", JsonConvert.SerializeObject(existAccount));

                    if (existAccount.Role == AccountRole.Admin)
                    {
                        return RedirectToAction("Dashboard", "Admin");
                    }
                    else if (existAccount.Role == AccountRole.Customer)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                TempData["ErrorMessage"] = "Mật khẩu không chính xác!";
                return RedirectToAction(nameof(Login));
            }
            TempData["ErrorMessage"] = "Username không tồn tại";
            return RedirectToAction(nameof(Login));
        }

        [Route("Register")]
        [Route("Auth/Register")]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RegisterPost(Account account)
        {
            if (ModelState.IsValid)
            {
                if (_context.Account.Any(e => e.Username == account.Username))
                {
                    TempData["ErrorMessage"] = "Username have exists";
                    return RedirectToAction(nameof(Register));
                }
                var salt = PasswordHandle.GetInstance().GenerateSalt();
                var passwordEncode = PasswordHandle.GetInstance().EncryptPassword(account.Password, salt);
                account.Salt = salt;
                account.Password = passwordEncode;

                _context.Add(account);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Login));
            }
            return RedirectToAction(nameof(Login));
        }

        [Route("Logout")]
        [Route("Auth/Logout")]
        public IActionResult Logout()
        {
            _session.SetString("user", "");
            _session.SetString("auth", "");
            _session.Remove("user");
            _session.Remove("auth");
            return RedirectToAction(nameof(Login));
        }


    }
}

ProjectSEM3/Views/Shared/_AdminMenu.cshtml
<ul class="sidebar-menu" data-widget="tree">
    <!-- Optionally, you can add icons to the links -->
    <li class='@(ViewData["Active"] == "Dashboard" ? "active": "")'><a asp-action="Dashboard" asp-controller="Admin"><i class="fa fa-dashboard"></i>  <span>Dashboard</span></a></li>
    <li class='@(ViewData["Active"] == "Admin" ? "active": "")'><a asp-action="Index" asp-controller="Admin"><i class="fa fa-user"></i> <span>Admins</span></a></li>
    <li class='@(ViewData["Active"] == "Users" ? "active": "")'><a asp-action="Index" asp-controller="Account"><i class="fa fa-users"></i>  <span>Users</span></a></li>
    <li class="@(ViewData["Active"] == "Authors" ? "active": "")"><a asp-action="Index" asp-controller="Authors"><i class="fa fa-bookmark"></i> <span>Authors</span></a></li>
    <li class="@(ViewData["Active"] == "Categories" ? "active": "")"><a asp-action="Index" asp-controller="Categories"><i class="fa fa-code-fork"></i> <span>Categories</span></a></li>
    <li class="@(ViewData["Active"] == "Books" ? "active": "")"><a asp-action="Index" asp-controller="Books"><i class="fa fa-book"></i> <span>Books</span></a></li>
    <li class="@(ViewData["Active"] == "Order" ? "active": "")"><a asp-action="Index" asp-controller="Order"><i class="fa fa-shopping-cart"></i> <span>Order</span></a></li>
    <li class="@(ViewData["Active"] == "Logout" ? "active": "")"><a asp-action="Logout" asp-controller="Auth"><i class="fa fa-sign-out"></i> <span>Logout</span></a></li>
</ul>

ProjectSEM3/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewData["Title"] - Online Book Store</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/images/favicon.png" />
    <link rel="stylesheet" href="~/Admin/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Admin/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/Admin/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Admin/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/Admin/dist/css/skins/skin-blue.min.css">
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <!--Tables Admin styles-->
    <link rel="stylesheet" href="~/Admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
    <!--Dashboard style-->
    <link rel="stylesheet" href="~/Admin/bower_components/morris.js/morris.css">
</head>
<body class="hold-transition skin-blue sidebar-mini sidebar-collapse">
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a asp-controller="Admin" asp-action="Dashboard" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini">AD</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg">Admin</span>
            </a>
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="~/Admin/dist/img/hotgirl.jpg" class="user-image" alt="User Image">
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">@ViewData["fullnameUser"]</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="~/Admin/dist/img/hotgirl.jpg" class="img-circle" alt="User Image">
                                    <p>
                                        NDV
                                        <small>Member since Nov. 2018</small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <li class="user-body">
                                    <div class="row">
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Account</a>
                                        </div>
                                    </div>
                                    <!-- /.row -->
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a asp-controller="Admin" asp-action="Profile" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a asp-controller="Admin" asp-action="LoginAdmin" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/Admin/dist/img/hotgirl.jpg" style="border-radius: 50%; height: 40px; " alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>@ViewData["fullnameUser"]</p>
                        <!-- Status -->
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- search form (Optional) -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- Sidebar Menu -->
                @Html.Partial("_AdminMenu")
                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            @RenderBody()

            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- Default to the left -->
            <strong>Copyright &copy; 2019 <a href="">NDV</a>.</strong>
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    <!-- jQuery 3 -->
    <script src="~/Admin/bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/Admin/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Admin/dist/js/adminlte.min.js"></script>
    <script src="~/Admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>