ProjectSEM3/Models/Dashboard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectSEM3.Models
{
    public class Dashboard
    {
        public int account_count { get; set; }
        public int author_count { get; set; }
        public int book_count { get; set; }
        public int order_count { get; set; }
    }
}

ProjectSEM3/Areas/Identity/Pages/Account/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ProjectSEM3.Areas.Identity.Pages.Account
{
    [AllowAnonymous]
    public class RegisterModel : PageModel
    {
        private readonly SignInManager<IdentityUser> _signInManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ILogger<RegisterModel> _logger;
        private readonly IEmailSender _emailSender;

        public RegisterModel(
            UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager,
            ILogger<RegisterModel> logger,
            IEmailSender emailSender)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string ReturnUrl { get; set; }

        public class InputModel
        {
            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        public void OnGet(string returnUrl = null)
        {
            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            if (ModelState.IsValid)
            {
                var user = new IdentityUser { UserName = Input.Email, Email = Input.Email };
                var result = await _userManager.CreateAsync(user, Input.Password);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User created a new account with password.");

                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    var callbackUrl = Url.Page(
                        "/Account/ConfirmEmail",
                        pageHandler: null,
                        values: new { userId = user.Id, code = code },
                        protocol: Request.Scheme);

                    await _emailSender.SendEmailAsync(Input.Email, "Confirm your email",
                        $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return LocalRedirect(returnUrl);
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

ProjectSEM3/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectSEM3.Data;
using ProjectSEM3.Models;

namespace ProjectSEM3.Controllers
{
    public class BooksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BooksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Books
        public async Task<IActionResult> Index()
        {
            return View(await _context.Book.ToListAsync());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(float? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            var category = _context.Category.ToList();
            ViewData["category"] = category;
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Snippet,Thumbnail,Price,Cover,Overview,Published,Hardcover,Language,Dimensions,CreatedAt,UpdatedAt,Status,Total,AuthorId")] Book book, string[] categoryId)
        {
            var category = _context.Category.ToList();
            ViewData["category"] = category;
            if (ModelState.IsValid)
            {
                book.AccountId = 4;
                _context.Add(book);
                await _context.SaveChangesAsync();

                foreach (var id in categoryId)
                {
                    var categoryFind = /*_context.Category.Find(id);*/ _context.Category.SingleOrDefault(c => c.Id.ToString() == id);
                    if (categoryFind != null)
                    {
                        BookCategory bookCategory = new BookCategory()
                        {
                            BookId = book.Id,
                            CategoryId = categoryFind.Id
                        };
                        _context.Add(bookCategory);
                        await _context.SaveChangesAsync();
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Snippet,Thumbnail,Price,Cover,Overview,Published,Hardcover,Language,Dimensions,CreatedAt,UpdatedAt,Status,Total,AuthorId")] Book book)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var book = await _context.Book.FindAsync(id);
            _context.Book.Remove(book);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookExists(float id)
        {
            return _context.Book.Any(e => e.Id == id);
        }
    }
}

ProjectSEM3/Views/Admin/Create.cshtml
@model ProjectSEM3.Models.Account

@{
    ViewData["Title"] = "Create";
    Layout = "_Layout2";
    ViewData["Active"] = "Admin";
}
<section class="content-header">
    <h6>
        <ol class="breadcrumb">
            <li><a asp-action="Dashboard" asp-controller="Admin"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a asp-action="Index" asp-controller="Admin"><i class="fa fa-user"></i> Account</a></li>
            <li class="active">Create</li>
        </ol>
    </h6>
</section>
<section class="content container-fluid">
    <div class="box box-info">
        <div class="box-header">
            <h3 class="box-title">Add Account</h3>
            <hr />
        </div>
        <div class="row">
            <div class="col-md-8">
                <form asp-action="Create" class="form-horizontal">
                    <div asp-validation-summary="ModelOnly" class="text-danger box-body"></div>
                    <div class="form-group">
                        <label asp-for="Username" class="control-label col-sm-2"></label>
                        <div class="col-sm-10">
                            <input asp-for="Username" class="form-control" />
                            <span asp-validation-for="Username" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label col-sm-2"></label>
                        <div class="col-sm-10">
                            <input asp-for="Password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                    </div>
                    
                    <div class="box-footer">
                        <div class="form-group col-sm-2">
                            <input type="submit" value="Create" class="btn btn-info" />
                        </div>
                        <div class="btn btn-default">
                            <a asp-action="Index">Back to List</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

ProjectSEM3/Views/Admin/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
    ViewData["Active"] = "Dashboard";
    Layout = "_Layout2";
}

<section class="content-header">
    <h1>
        Dashboard

    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>@Model.account_count</h3>
                    <p>Account</p>
                </div>
                <div class="icon">
                    <i class="fa fa-users"></i>
                </div>
                <a asp-controller="Admin" asp-action="Index" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-green">
                <div class="inner">
                    <h3>@Model.author_count<sup style="font-size: 20px"></sup></h3>
                    <p>Authors</p>
                </div>
                <div class="icon">
                    <i class="fa fa-users"></i>
                </div>
                <a asp-controller="Authors" asp-action="Index" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h3>@Model.book_count</h3>
                    <p>Books</p>
                </div>
                <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                </div>
                <a asp-controller="Books" asp-action="Index" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
        <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-red">
                <div class="inner">
                    <h3>@Model.order_count</h3>
                    <p>Orders</p>
                </div>
                <div class="icon">
                    <i class="ion ion-clipboard"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <!-- ./col -->
    </div>
    <!-- /.row -->
    <!-- Main row -->
    <div class="row">
        <!-- Left col -->
        <section class="col-lg-7 connectedSortable">
            <!-- Custom tabs (Charts with tabs)-->
            <!-- DONUT CHART -->
            <div class="box box-danger">
                <div class="box-header with-border">
                    <h3 class="box-title">Donut Chart</h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                    </div>
                </div>
                <div class="box-body chart-responsive">
                    <div class="chart" id="sales-chart" style="height: 300px; position: relative;"></div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.nav-tabs-custom -->
        </section>
        <!-- /.Left col -->
        <!-- right col (We are only adding the ID to make the widgets sortable)-->
        <section class="col-lg-5 connectedSortable">
            <!-- TO DO List -->
            <div class="box box-primary">
                <div class="box-header">
                    <i class="ion ion-clipboard"></i>
                    <h3 class="box-title">To Do List</h3>
                    <div class="box-tools pull-right">
                        <ul class="pagination pagination-sm inline">
                            <li><a href="#">&laquo;</a></li>
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">&raquo;</a></li>
                        </ul>
                    </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <!-- See dist/js/pages/dashboard.js to activate the todoList plugin -->
                    <ul class="todo-list">
                        <li>
                            <!-- drag handle -->
                            <span class="handle">
                                <i class="fa fa-ellipsis-v"></i>
                                <i class="fa fa-ellipsis-v"></i>
                            </span>
                            <!-- checkbox -->
                            <input type="checkbox" value="">
                            <!-- todo text -->
                            <span class="text">1 Account Has Been Registered</span>
                            <!-- Emphasis label -->
                            <small class="label label-danger"><i class="fa fa-clock-o"></i> 2 mins</small>
                            <!-- General tools such as edit or delete-->
                            <div class="tools">
                                <i class="fa fa-edit"></i>
                                <i class="fa fa-trash-o"></i>
                            </div>
                        </li>
                        <li>
                            <span class="handle">
                                <i class="fa fa-ellipsis-v"></i>
                                <i class="fa fa-ellipsis-v"></i>
                            </span>
                            <input type="checkbox" value="">
                            <span class="text">New Order</span>
                            <small class="label label-info"><i class="fa fa-clock-o"></i> 4 hours</small>
                            <div class="tools">
                                <i class="fa fa-edit"></i>
                                <i class="fa fa-trash-o"></i>
                            </div>
                        </li>
                        <li>
                            <span class="handle">
                                <i class="fa fa-ellipsis-v"></i>
                                <i class="fa fa-ellipsis-v"></i>
                            </span>
                            <input type="checkbox" value="">
                            <span class="text">10 Books Has Been Update</span>
                            <small class="label label-warning"><i class="fa fa-clock-o"></i> 1 day</small>
                            <div class="tools">
                                <i class="fa fa-edit"></i>
                                <i class="fa fa-trash-o"></i>
                            </div>
                        </li>
                        <li>
                            <span class="handle">
                                <i class="fa fa-ellipsis-v"></i>
                                <i class="fa fa-ellipsis-v"></i>
                            </span>
                            <input type="checkbox" value="">
                            <span class="text">1 Authors Has Been Update</span>
                            <small class="label label-success"><i class="fa fa-clock-o"></i> 3 days</small>
                            <div class="tools">
                                <i class="fa fa-edit"></i>
                                <i class="fa fa-trash-o"></i>
                            </div>
                        </li>
                        <li>
                            <span class="handle">
                                <i class="fa fa-ellipsis-v"></i>
                                <i class="fa fa-ellipsis-v"></i>
                            </span>
                            <input type="checkbox" value="">
                            <span class="text">Any other Activity</span>
                            <small class="label label-primary"><i class="fa fa-clock-o"></i> 1 week</small>
                            <div class="tools">
                                <i class="fa fa-edit"></i>
                                <i class="fa fa-trash-o"></i>
                            </div>
                        </li>
                        <li>
                            <span class="handle">
                                <i class="fa fa-ellipsis-v"></i>
                                <i class="fa fa-ellipsis-v"></i>
                            </span>
                            <input type="checkbox" value="">
                            <span class="text">Any other Activity</span>
                            <small class="label label-default"><i class="fa fa-clock-o"></i> 1 month</small>
                            <div class="tools">
                                <i class="fa fa-edit"></i>
                                <i class="fa fa-trash-o"></i>
                            </div>
                        </li>
                    </ul>
                </div>
                <!-- /.box-body -->
                <div class="box-footer clearfix no-border">
                    <button type="button" class="btn btn-default pull-right"><i class="fa fa-plus"></i> Add item</button>
                </div>
            </div>
            <!-- /.box -->
        </section>
        <!-- right col -->
    </div>
    <!-- /.row (main row) -->
</section>
@section Scripts{
    <script src="~/Admin/bower_components/raphael/raphael.min.js"></script>
    <script src="~/Admin/bower_components/morris.js/morris.min.js"></script>
    <script>
  $(function () {
    "use strict";
    //DONUT CHART
    var donut = new Morris.Donut({
      element: 'sales-chart',
      resize: true,
        colors: ["#3c8dbc", "#00a65a", "#f39c12", "#dd4b39" ],
      data: [
        {label: "Accounts", value: @Model.account_count},
        {label: "Authors", value: @Model.author_count},
        { label: "Books", value: @Model.book_count},
        {label: "Orders", value: @Model.order_count}
      ],
      hideHover: 'auto'
    });
  });
    </script>
}

ProjectSEM3/Views/Admin/Delete.cshtml
@model ProjectSEM3.Models.Account

@{
    ViewData["Title"] = "Delete";
    Layout = "_Layout2";
    ViewData["Active"] = "Admin";
}

<section class="content-header">
    <h6>
        <ol class="breadcrumb">
            <li><a asp-action="Dashboard" asp-controller="Admin"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a asp-action="Index" asp-controller="Admin"><i class="fa fa-user"></i> Account</a></li>
            <li class="active">Delete</li>
        </ol>
    </h6>
    <h3>Are you sure you want to delete this?</h3>
</section>
<section class="content container-fluid">
    <div class="box box-danger">
        <div class="box-header">
            <h4>Account</h4>
            <hr />
        </div>
        <div class="row">
            <div class="col-md-8">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Username)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Username)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Password)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Password)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Status)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Status)
                    </dd>
                </dl>
                <form asp-action="Delete" >
                    <div class="form-group col-sm-2">
                        <input type="hidden" asp-for="Id" />
                        <input type="submit" value="Delete" class="btn btn-danger" />
                    </div>
                    <div class="form-group btn btn-default">
                        <a asp-action="Index">Back to List</a>
                    </div>
               </form> 
            </div>
        </div>
    </div>
</section>

ProjectSEM3/Views/Admin/Details.cshtml
@model ProjectSEM3.Models.Account

@{
    ViewData["Title"] = "Details";
    Layout = "_Layout2";
    ViewData["Active"] = "Admin";
}

<section class="content-header">
    <h6>
        <ol class="breadcrumb">
            <li><a asp-action="Dashboard" asp-controller="Admin"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a asp-action="Index" asp-controller="Admin"><i class="fa fa-user"></i> Account</a></li>
            <li class="active">Details</li>
        </ol>
    </h6>
</section>

<section class="content container-fluid">
    <div class="box box-info">
        <div class="box-header">
            <h4 class="box-title">Account</h4>
            <hr />
        </div>
        <div class="row">
            <div class="col-md-8">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Username)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Username)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Password)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Password)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Status)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Status)
                    </dd>
                </dl>
            </div>
        </div>
        <div class="box-footer">
            <div class="form-group col-sm-1">
                <a class="btn btn-success" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
            </div>
            <div class="form-group btn btn-default">
                <a asp-action="Index">Back to List</a>
            </div>
        </div>
    </div>
</section>

ProjectSEM3/Views/Admin/Edit.cshtml
@model ProjectSEM3.Models.Account

@{
    ViewData["Title"] = "Edit";
    Layout = "_Layout2";
    ViewData["Active"] = "Admin";
}
<section class="content-header">
    <h6>
        <ol class="breadcrumb">
            <li><a asp-action="Dashboard" asp-controller="Admin"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a asp-action="Index" asp-controller="Admin"><i class="fa fa-user"></i> Account</a></li>
            <li class="active">Edit</li>
        </ol>
    </h6>
</section>
<section class="content container-fluid">
    <div class="box box-info">
        <div class="box-header">
            <h4 class="box-title">Account</h4>
            <hr/>
        </div>
        <div class="row">
            <div class="col-md-8">
                <form asp-action="Edit" class="form-horizontal">
                    <div asp-validation-summary="ModelOnly" class="text-danger box-body"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group">
                        <label asp-for="Username" class="control-label col-sm-2"></label>
                        <div class="col-sm-10">
                            <input asp-for="Username" class="form-control" />
                            <span asp-validation-for="Username" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label col-sm-2"></label>
                        <div class="col-sm-10">
                            <input asp-for="Password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Status" class="control-label col-sm-2"></label>
                        <div class="col-sm-10">
                            <select asp-for="Status" class="form-control">
                                <option value="1">Active</option>
                                <option value="2">Deactive</option>
                            </select>
                            <span asp-validation-for="Status" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="form-group col-sm-2">
                            <input type="submit" value="Save" class="btn btn-warning" />
                        </div>
                        <div class="form-group btn btn-default">
                            <a asp-action="Index">Back to List</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

ProjectSEM3/Views/Admin/LoginAdmin.cshtml
@model ProjectSEM3.Models.Account

@{
    Layout = null;
}
<environment include="Development">
    <link rel="stylesheet" href="~/css/FormLayout.css" /><link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="~/css/font.css" rel="stylesheet" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
</environment>
<style>
    .alert_header {
        position: fixed;
        top: 50px;
        left: 50%;
        transform: translateX(-50%);
        font-size: 14px;
    }
</style>
<div class="alert_header">
    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["ErrorMessage"].ToString()
        </div>
    }
</div>
<div class="login_dialog">

    <a class="boxclose"></a>

    <form asp-action="SignIn">
        <h2>Please Login</h2>
        <label for="login_user"> Username</label>
        <input type="text" asp-for="Username" />
        <label for="pass_user"> Password </label>
        <input type="password" asp-for="Password" />
        <label for="rememberme" id="lb_rememberme">
            <input name="rememberme" type="checkbox" id="rememberme" value="forever" />
            Remember Me
        </label>
        <input type="submit" name="login_submit" value="LOGIN" class="login_submit" />
        <label for="register">
            <a asp-action="Register">Register new account</a>
        </label>
        <div class="social-login">


        </div>
    </form>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}